name: Build Binary

on:
  workflow_dispatch:

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Haxe
        run: |
          set -ex
          sudo add-apt-repository ppa:haxe/releases -y
          sudo apt-get update
          sudo apt-get install haxe -y
          mkdir ~/haxelib && haxelib setup ~/haxelib

      - name: Cache haxelib libraries
        uses: actions/cache@v2
        with:
          path: |
            ~/haxelib
          key: ${{ runner.os }}-haxelib-${{ hashFiles('**/haxelib.json') }}
          restore-keys: |
            ${{ runner.os }}-haxelib-

      - name: Install dependencies
        run: |
          set -ex
          haxelib --always --quiet install all

      - name: Build native binary
        run: |
          set -ex
          mkdir build
          mkdir bin
          haxelib --always --quiet install hxcpp
          haxe targets/cpp.hxml -cmd "cp build/cpp/Main bin/merge-json-${{ runner.os }}"

      - name: Archive build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-binary
          path: bin/*

  mac-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Haxe
        run: |
          set -ex
          brew install npm
          sudo npm install -g lix
          lix download haxe 4.1.5
          lix use haxe 4.1.5

      - name: Cache haxelib libraries
        uses: actions/cache@v2
        with:
          path: |
            ~/haxelib
          key: ${{ runner.os }}-haxelib-${{ hashFiles('**/haxelib.json') }}
          restore-keys: |
            ${{ runner.os }}-haxelib-

      - name: Install dependencies
        run: |
          set -ex
          haxelib --always --quiet install all

      - name: Build native binary
        run: |
          set -ex
          mkdir build
          mkdir bin
          haxelib --always --quiet install hxcpp
          haxe targets/cpp.hxml -cmd "cp build/cpp/Main bin/merge-json-${{ runner.os }}"

      - name: Archive build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-binary
          path: bin/*
