name: BuildAndTest

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Haxe
        run: |
          set -ex
          sudo add-apt-repository ppa:haxe/releases -y
          sudo apt-get update
          sudo apt-get install haxe -y
          mkdir ~/haxelib && haxelib setup ~/haxelib

      - name: Install dependencies
        run: |
          set -ex
          haxelib --always --quiet install all

      - name: Run Simple Integration Test
        run: |
          set -ex
          mkdir build
          haxe tests.hxml

      - name: Archive test output 
        uses: actions/upload-artifact@v2
        with:
          name: merged_result 
          path: build/output.json 